spring.application.name=subscriber
server.port=8072

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=amquser
spring.activemq.password=amqpwd
spring.activemq.packages.trust-all=true

app.alumno.id=alumno1
