spring.application.name=publisher
server.port=8071

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=amquser
spring.activemq.password=amqpwd

spring.activemq.packages.trust-all=true
